#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

#include <wx/dcclient.h>
#include <wx/dir.h>
#include <wx/dirdlg.h>
#include <wx/dcmemory.h>
#include <vector>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_buttonLeftOnButtonClick( wxCommandEvent& event );
		void m_scrolledWindow1OnPaint( wxPaintEvent& event );
		void m_buttonRightOnButtonClick( wxCommandEvent& event );
		void m_buttonFolderOnButtonClick( wxCommandEvent& event );
		void m_buttonPrintOnButtonClick( wxCommandEvent& event );
		void m_textCtrlWidthOnText( wxCommandEvent& event );
		void m_textCtrlHeightOnText( wxCommandEvent& event );
		void m_textCtrlRowsOnText( wxCommandEvent& event );
		void m_textCtrlCollsOnText( wxCommandEvent& event );
		void m_textCtrlCommentOnText( wxCommandEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

		wxArrayString GetSortedBmpFileNames(const wxString& folderPath);
		wxString ShortenFileName(const wxString& name, int maxWidth, wxDC& dc);
		wxBitmap CreateIndexPageBitmap(
			const wxArrayString& fileNames,
			const wxString& folderPath,
			const wxString& comment,
			int pageWidth,
			int pageHeight,
			int rows,
			int cols,
			int thumbW,
			int thumbPhotoH,
			int thumbH,
			int pageNum
		);
		void RebuildIndexPage();

		wxString m_selectedFolder;
		wxBitmap m_indexPageBitmap;
		std::vector<wxBitmap> m_indexPageBitmaps;
		int m_currentPage = 0;
};

#endif // __GUIMyFrame1__
